name: Docs builder
on: push

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm install -g grunt-cli
      - run: npm install --safe-dev
      - run: grunt docs
      - uses: actions/upload-artifact@v2
        with:
          name: full-docs-artifact
          path: ./out
      - uses: actions/upload-artifact@v2
        with:
          name: core-engine-artifact
          path: ./out/core-engine.d.ts